name: 'Test multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

env:
  DH_REGISTRY: docker.io
  CONTAINER_TAG: initial

jobs:
  test-on-linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    permissions:
      contents: read
      packages: write
    container:
      image: '${{ env.DH_REGISTRY }}/${{ secrets.DH_USER }}/${{ env.REPOSITORY_NAME }}:${{ env.CONTAINER_TAG }}'
      options:
        -v /dev:/dev
        -u root

    steps:
      - name: 'Set parameters to GITHUB_ENV'
        shell: bash
        run: |
          echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> ${GITHUB_ENV}
          echo "GITHUB_ENV:"
          cat ${GITHUB_ENV}
      - name: 'Docker image test'
        shell: bash
        run: |
          echo -ne "COPILOT_CLI_VERSION="
          copilot --version | awk '{print $NF}' | head -n 1
